/*jslint nomen:true, browser:true*/
/*jshint esnext:true*/
/*global Y*/

// classes
import ControllerNews from 'controllers/news';
import ControllerPhoto from 'controllers/photo';
import ControllerPhotos from 'controllers/photos';
import ControllerSearch from 'controllers/search';

import ModelNews from 'models/news';
import ModelPost from 'models/post';
import ModelPhotos from 'models/photos';
import ModelPhoto from 'models/photo';

import RoutePhoto from 'routes/photo';
import RouteSearch from 'routes/search';

import ViewAbout from 'views/about';
import ViewHome from 'views/home';
import ViewPhotos from 'views/photos';
import ViewPhoto from 'views/photo';
import ViewNews from 'views/news';
import ViewSearch from 'views/search';

import {Controllers, Models, Routes, Views} from 'pn';

Controllers.register('news', ControllerNews);
Controllers.register('photo', ControllerPhoto);
Controllers.register('photos', ControllerPhotos);
Controllers.register('search', ControllerSearch);

Models.register('news',   ModelNews);
Models.register('post',   ModelPost);
Models.register('photos', ModelPhotos);
Models.register('photo',  ModelPhoto);

Routes.register('photo', RoutePhoto);
Routes.register('search', RouteSearch);

Views.register('about',  ViewAbout);
Views.register('home',   ViewHome);
Views.register('news',   ViewNews);
Views.register('photos', ViewPhotos);
Views.register('photo',  ViewPhoto);
Views.register('search', ViewSearch);

import {BaseApp} from 'base-app';
import {Base} from 'base-build';
import {config} from 'yui';

var MainView = Base.create('main-view', BaseApp, [], {

    events: {
        '.search-box': {
            'keypress': 'enter'
        }
    },
    // TODO
    // views config should not be generated by the server at all :)
    views: {
        home: {
            type: ViewHome,
            preserve: true
        },
        news: {
            type: ViewNews,
            preserve: true
        },
        photos: {
            type: ViewPhotos,
            preserve: true
        },
        photo: {
            type: ViewPhoto,
            preserve: false
        },
        about: {
            type: ViewAbout,
            preserve: true
        },
        search: {
            type: ViewSearch,
            preserve: false
        }
    },

    transitions: {
        navigate: 'fade',
        toChild: 'fade',
        toParent: 'fade'
    },

    initializer: function () {
        var container = this.get('container'),
            searchBox = container.one('.search-box');

        // Set up and cache often-used DOM elements as attributes
        this.set('searchBox', searchBox);

        // Set up any other necessary

        // this.on('photo:navigate', this.navigatePhotos);
    },

    render: function (options) {
        MainView.superclass.render.apply(this, arguments);

        options = options || {};

        if (options.rendered) {
            return this;
        }

        return this;
    },

    enter: function (e) {
        var ENTER_KEY = 13;

        if (e.keyCode === ENTER_KEY) {
            e.preventDefault();
            this.searchQuery();
        }
    },

    searchQuery: function () {
        var query = this.get('searchBox').get('value');

        if (query) {
            this.navigate('/search?q=' + query);
        } else {
            this.navigate('/search');
        }
    },

    navigatePhotos: function (e) {
        this.navigate('/photo/' + e.photoId);
    }
}, {

    ATTRS: {}

});

Y.MainView = MainView;
config.global.MainView = MainView;
export default MainView;
