/*jslint nomen:true, browser:true*/
/*jshint esnext:true*/

// classes
import ControllerNews from 'controllers/news';
import ControllerPhotos from 'controllers/photos';
import ControllerSearch from 'controllers/search';

import ModelNews from 'models/news';
import ModelPost from 'models/post';
import ModelPhotos from 'models/photos';
import ModelPhoto from 'models/photo';

import ViewAbout from 'views/about';
import ViewHome from 'views/home';
import ViewPhotos from 'views/photos';
import ViewNews from 'views/news';
import ViewSearch from 'views/search';

import {Controllers, Views, Models} from 'pn';

Controllers.register('news', ControllerNews);
Controllers.register('photos', ControllerPhotos);
Controllers.register('search', ControllerSearch);

Models.register('news',   ModelNews);
Models.register('post',   ModelPost);
Models.register('photos', ModelPhotos);
Models.register('photo',  ModelPhoto);

Views.register('about',  ViewAbout);
Views.register('home',   ViewHome);
Views.register('news',   ViewNews);
Views.register('photos', ViewPhotos);
Views.register('search', ViewSearch);

import {BaseApp} from 'base-app';
import {Base} from 'base-build';
import {config} from 'yui';

var MainView = Base.create('main-view', BaseApp, [], {

    events: {
        '.search-box': {
            'keypress': 'enter'
        }
    },
    // TODO
    // views config should not be generated by the server at all :)
    views: {
        home: {
            type: ViewHome,
            preserve: true
        },
        news: {
            type: ViewNews,
            preserve: true
        },
        photos: {
            type: ViewPhotos,
            preserve: true
        },
        about: {
            type: ViewAbout,
            preserve: true
        },
        search: {
            type: ViewSearch,
            preserve: true
        }
    },

    transitions: {
        navigate: 'fade',
        toChild: 'fade',
        toParent: 'fade'
    },

    initializer: function () {
        var container = this.get('container'),
            searchBox = container.one('.search-box');

        // Set up and cache often-used DOM elements as attributes
        this.set('searchBox', searchBox);

        // Set up any other necessary

        this.on('photosView:next', this.nextPhotos);
        this.on('photosView:prev', this.prevPhotos);
    },

    render: function (options) {
        var viewContainer,
            container;

        MainView.superclass.render.apply(this, arguments);

        options = options || {};

        if (options.rendered) {
            return this;
        }

        return this;
    },

    enter: function (e) {
        var ENTER_KEY = 13;

        if (e.keyCode === ENTER_KEY) {
            e.preventDefault();
            this.searchQuery();
        }
    },

    searchQuery: function () {
        var query = this.get('searchBox').get('value');

        if (query) {
            this.navigate('/search?q=' + query);
        } else {
            this.navigate('/search');
        }
    },

    nextPhotos: function () {
        var model;
        model = this.get('model');
        model.load();
    },

    prevPhotos: function () {
        var model;
        model = this.get('model');
        model.load();
    }

}, {

    ATTRS: {}

});

Y.MainView = MainView;
config.global.MainView = MainView;
export default MainView;
